import { useMemo } from "react";
import { toast } from "sonner";
import { Check, Download, FileCheck2, PenLine, ShieldCheck } from "lucide-react";
import PlanningWorkspace from "@/components/PlanningWorkspace";
import { useEventPlanning } from "@/lib/eventPlanning";
import { computeBilling } from "@/lib/billing";
import { currency, fmtDate } from "@/data/mockData";
import { cn } from "@/lib/utils";

type ContractStatus = "done" | "active" | "pending";

const CONTRACT_STEPS: { no: string; label: string; blurb: string; status: ContractStatus }[] = [
  { no: "01", label: "Proposal accepted", blurb: "Client signed off on the awarded proposal.", status: "done" },
  { no: "02", label: "Contract drafted", blurb: "Event agreement generated by sales ops.", status: "done" },
  { no: "03", label: "Legal review", blurb: "Redlines and terms under review.", status: "active" },
  { no: "04", label: "Signatures", blurb: "Client execution & countersignature.", status: "pending" },
  { no: "05", label: "Deposit & date hold", blurb: "Deposit invoice and confirmed hold.", status: "pending" },
];

function DetailRow({ label, value, mono }: { label: string; value: string; mono?: boolean }) {
  return (
    <div className="flex items-baseline justify-between gap-4 py-2.5">
      <dt className="text-[11px] uppercase tracking-[0.16em] text-ink-muted">{label}</dt>
      <dd className={cn("text-right text-sm text-ink", mono && "font-mono text-xs")}>{value}</dd>
    </div>
  );
}

export default function Contract() {
  const { event } = useEventPlanning();
  const b = useMemo(() => computeBilling(event.estValue), [event.estValue]);

  const action = (
    <button
      onClick={() => toast("Downloading master event contract…")}
      className="inline-flex items-center gap-2 rounded-full bg-ink px-4 py-2 text-xs font-semibold uppercase tracking-[0.12em] text-paper hover:bg-ink/90"
    >
      <Download className="h-3.5 w-3.5" /> Download contract
    </button>
  );

  const terms = [
    { label: "Service agreement", value: "Master Event Services Agreement" },
    { label: "Effective", value: fmtDate("2026-04-22") },
    { label: "Governing law", value: "State of California, USA" },
    { label: "Auto-renew", value: "None single-event term" },
  ];

  const policies = [
    "Refundable hold up to 90 days before the event start date.",
    "Final guaranteed headcount due 14 days prior; billed at the greater of guaranteed or actual.",
    "Room block attrition allowance of 10% with no penalty.",
    "Force majeure relief for events beyond reasonable control.",
  ];

  return (
    <PlanningWorkspace activeStep="contract" action={action}>
      {/* Contract tracker */}
      <div className="overflow-hidden rounded-xl border border-border-subtle bg-paper shadow-card">
        <div className="border-b border-border-subtle px-6 py-4">
          <div className="text-[10px] uppercase tracking-[0.25em] text-ink-muted">Contract tracking</div>
          <h3 className="mt-1 font-serif text-lg text-ink">From proposal to signed hold</h3>
        </div>
        <ol className="grid gap-px bg-border-subtle sm:grid-cols-5">
          {CONTRACT_STEPS.map((step) => (
            <li key={step.no} className="bg-paper px-5 py-5">
              <span
                className={cn(
                  "grid h-7 w-7 place-items-center rounded-full border text-[10px] font-semibold",
                  step.status === "done"
                    ? "border-copper bg-copper text-paper"
                    : step.status === "active"
                      ? "border-copper bg-copper/10 text-copper"
                      : "border-border-default bg-paper text-ink-muted",
                )}
              >
                {step.status === "done" ? <Check className="h-3.5 w-3.5" strokeWidth={3} /> : step.no}
              </span>
              <div
                className={cn(
                  "mt-3 text-sm font-medium leading-tight",
                  step.status === "pending" ? "text-ink-soft" : "text-ink",
                )}
              >
                {step.label}
              </div>
              <div className="mt-1 text-[11px] leading-snug text-ink-muted">{step.blurb}</div>
              {step.status === "active" && (
                <span className="mt-2 inline-block rounded-full bg-copper/10 px-2 py-0.5 text-[9px] font-semibold uppercase tracking-[0.16em] text-copper">
                  In progress
                </span>
              )}
            </li>
          ))}
        </ol>
      </div>

      {/* Parties + event summary */}
      <div className="mt-6 grid gap-6 lg:grid-cols-2">
        <div className="rounded-xl border border-border-subtle bg-paper p-6 shadow-card">
          <div className="text-[10px] uppercase tracking-[0.25em] text-ink-muted">Parties</div>
          <h3 className="mt-1 font-serif text-lg text-ink">Agreement between</h3>
          <div className="mt-4 grid gap-4 sm:grid-cols-2">
            <div className="rounded-lg border border-border-subtle bg-canvas/50 p-4">
              <div className="text-[10px] uppercase tracking-[0.18em] text-ink-muted">Property</div>
              <div className="mt-1 font-medium text-ink">Nobu Hotel Los Cabos</div>
              <div className="mt-0.5 text-xs text-ink-soft">Events & Catering Department</div>
            </div>
            <div className="rounded-lg border border-border-subtle bg-canvas/50 p-4">
              <div className="text-[10px] uppercase tracking-[0.18em] text-ink-muted">Client</div>
              <div className="mt-1 font-medium text-ink">{event.client}</div>
              <div className="mt-0.5 text-xs text-ink-soft">
                {event.contactName} · {event.contactEmail}
              </div>
            </div>
          </div>
        </div>

        <div className="rounded-xl border border-border-subtle bg-paper p-6 shadow-card">
          <div className="text-[10px] uppercase tracking-[0.25em] text-ink-muted">Event summary</div>
          <h3 className="mt-1 font-serif text-lg text-ink">{event.eventName}</h3>
          <dl className="mt-3 divide-y divide-border-subtle">
            <DetailRow label="Venue" value={event.venue} />
            <DetailRow
              label="Dates"
              value={`${fmtDate(event.arrival)} – ${fmtDate(event.departure)}`}
            />
            <DetailRow label="Peak rooms" value={`${event.peakRooms} rooms`} />
            <DetailRow label="Meeting space" value={`${event.meetingSpaceSqft.toLocaleString()} sq ft`} />
            <DetailRow label="Contract value" value={currency(b.baseContract)} />
          </dl>
        </div>
      </div>

      {/* Terms + deposit schedule */}
      <div className="mt-6 grid gap-6 lg:grid-cols-2">
        <div className="rounded-xl border border-border-subtle bg-paper p-6 shadow-card">
          <div className="text-[10px] uppercase tracking-[0.25em] text-ink-muted">Key terms</div>
          <h3 className="mt-1 font-serif text-lg text-ink">Agreement details</h3>
          <dl className="mt-3 divide-y divide-border-subtle">
            {terms.map((t) => (
              <DetailRow key={t.label} label={t.label} value={t.value} />
            ))}
          </dl>
          <div className="mt-4 rounded-lg bg-canvas/60 p-4">
            <div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-ink-muted">
              <ShieldCheck className="h-3.5 w-3.5 text-copper" /> Policies
            </div>
            <ul className="mt-2 space-y-1.5">
              {policies.map((p) => (
                <li key={p} className="flex items-start gap-2 text-xs leading-relaxed text-ink-soft">
                  <FileCheck2 className="mt-0.5 h-3.5 w-3.5 flex-none text-copper" /> {p}
                </li>
              ))}
            </ul>
          </div>
        </div>

        <div className="rounded-xl border border-border-subtle bg-paper p-6 shadow-card">
          <div className="text-[10px] uppercase tracking-[0.25em] text-ink-muted">Deposit & payment schedule</div>
          <h3 className="mt-1 font-serif text-lg text-ink">Milestones</h3>
          <ul className="mt-3 divide-y divide-border-subtle">
            {b.payments.map((p) => (
              <li key={p.id} className="flex items-center justify-between gap-4 py-3">
                <div>
                  <div className="text-sm text-ink">{p.label}</div>
                  <div className="text-[11px] text-ink-muted">Due {fmtDate(p.due)} · {p.method}</div>
                </div>
                <div className="flex items-center gap-3">
                  <span className="font-medium text-ink">{currency(p.amount)}</span>
                  <span
                    className={cn(
                      "rounded-full px-2 py-0.5 text-[10px] uppercase tracking-[0.15em]",
                      p.status === "paid" ? "bg-success-soft text-success" : "bg-warning-soft text-warning",
                    )}
                  >
                    {p.status === "paid" ? "Paid" : "Scheduled"}
                  </span>
                </div>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Signatures */}
      <div className="mt-6 rounded-xl border border-border-subtle bg-paper p-6 shadow-card">
        <div className="text-[10px] uppercase tracking-[0.25em] text-ink-muted">Signatures</div>
        <h3 className="mt-1 font-serif text-lg text-ink">Execution</h3>
        <div className="mt-4 grid gap-4 sm:grid-cols-2">
          <div className="rounded-lg border border-border-subtle p-4">
            <div className="flex items-center gap-2 text-sm font-medium text-ink">
              <Check className="h-4 w-4 text-success" /> Nobu Hotel Los Cabos
            </div>
            <div className="mt-1 text-xs text-ink-soft">Countersigned · {fmtDate("2026-04-23")}</div>
          </div>
          <div className="rounded-lg border border-dashed border-copper/50 bg-copper/5 p-4">
            <div className="flex items-center gap-2 text-sm font-medium text-ink">
              <PenLine className="h-4 w-4 text-copper" /> {event.client}
            </div>
            <div className="mt-1 text-xs text-ink-soft">Awaiting client signature</div>
            <button
              onClick={() => toast.success("Signature request sent to " + event.contactEmail)}
              className="mt-3 inline-flex items-center gap-1.5 rounded-full border border-ink px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[0.14em] text-ink transition hover:bg-ink hover:text-paper"
            >
              Send for signature
            </button>
          </div>
        </div>
      </div>
    </PlanningWorkspace>
  );
}
